### ISSUE TITLE
`create` and `join` command sometimes fails due to Monitor target aborted

### ISSUE THREAD

**Issue by shinnya** [frugalos/frugalos#65]
Error:

```console
Jan 11 15:16:56.587 INFO [FINISH] create, server: new_frugalos_cluster_boss@127.0.0.1:14278, module: frugalos_config::cluster:170
thread '<unnamed>' panicked at 'Error: Other (cause; Monitor target aborted)
HISTORY:
  [0] at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fibers_rpc-0.2.17/src/rpc_server.rs:404
  [1] at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fibers_rpc-0.2.17/src/rpc_server.rs:281
', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/frugalos_config-0.3.0/src/cluster.rs:153:48
```

**Comment by shinnya** [comment]
This issue can be reproduced more frequently if waiting for logging in `main.rs` like below.

```rust
        track_try_unwrap!(frugalos_config::cluster::create(&logger, server, data_dir));
        // NOTE: ログ出力(非同期)用に少し待機
       std::thread::sleep(std::time::Duration::from_millis(100));
```

**Comment by shinnya** [comment]
I suspect that the root cause of the issue is that `fibers_rpc::Server` doesn't drop holding `polls`(by `mio`) because `fibers::executor::ThreadPoolExecutor` never stop the server(i.e. the running future) when the current process exits.

https://github.com/shinnya/fibers_rpc/commit/8d79176250e42d77e82550370834e3bd9dade79f

The above commit adds `ServerHandle::shutdown` method and can be used as:

```console
// frugalos_config/src/cluster.rs
    // RPC サーバーを停止
    let monitor = executor.spawn_monitor(rpc_server_handle.shutdown(Duration::from_millis(10)));
    let result = track!(executor.run_fiber(monitor).map_err(Error::from))?;
    track!(result.map_err(Error::from))?;
```

These changes seem to fix the issue.
